version: "3"

services:
    postgres:
        image: postgres:latest
        container_name: atec_postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: atec
            POSTGRES_PASSWORD: pwd
            POSTGRES_DB: aulateschnikde
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
